"""
Secret detection patterns organized by category.
Used by paste_monitor.py, google_dorker.py, and oops_scanner.py

Categories:
  - crypto_exchange: Binance, Coinbase, Kraken, Bybit, Kucoin, Bisq, Coinspot, FTX
  - crypto_wallet: BTC/ETH/SOL private keys, seed phrases, wallet.dat
  - social_media: Facebook, Twitter, Instagram, Discord, Telegram, Snapchat, TikTok, LinkedIn, Reddit
  - telco_australian: Telstra, Optus, Vodafone AU, Twilio
  - server_infrastructure: AWS, GCP, Azure, DigitalOcean, private keys
  - database: MongoDB, PostgreSQL, MySQL, Redis
  - payment: Stripe, PayPal, Square, Razorpay
  - google_accounts: OAuth, Service Account, API key, Firebase, GCP
  - microsoft_accounts: Azure AD, Microsoft Graph, Outlook, Teams, Azure Storage
  - ai_services: OpenAI, Anthropic, HuggingFace, Replicate, Together AI
"""

PATTERNS = {
    "crypto_exchange": [
        {"name": "Binance API Key", "regex": r"BINANCE[_]?API[_]?KEY\s*[=:]\s*['\"]?([A-Za-z0-9]{64})['\"]?", "severity": "critical", "method": "Binance API key for trading/withdrawal. Pair with secret key to execute trades, check balances, and withdraw funds.", "disclosure": "Binance Security: security@binance.com"},
        {"name": "Binance Secret Key", "regex": r"BINANCE[_]?SECRET[_]?KEY\s*[=:]\s*['\"]?([A-Za-z0-9]{64})['\"]?", "severity": "critical", "method": "Binance secret key - signs API requests. Full account control including withdrawals.", "disclosure": "Binance Security: security@binance.com"},
        {"name": "Coinbase API Key", "regex": r"COINBASE[_]?API[_]?KEY\s*[=:]\s*['\"]?([a-f0-9]{24,64})['\"]?", "severity": "critical", "method": "Coinbase API key for account access, trading, and wallet operations. Can buy/sell/withdraw crypto.", "disclosure": "Coinbase Security: https://www.coinbase.com/security"},
        {"name": "Coinbase Secret", "regex": r"COINBASE[_]?API[_]?SECRET\s*[=:]\s*['\"]?([A-Za-z0-9+/=]{24,64})['\"]?", "severity": "critical", "method": "Coinbase API secret - signs requests for trading and withdrawal endpoints.", "disclosure": "Coinbase Security: https://www.coinbase.com/security"},
        {"name": "Coinbase Access Token", "regex": r"COINBASE[_]?ACCESS[_]?TOKEN\s*[=:]\s*['\"]?([A-Za-z0-9]{64})['\"]?", "severity": "critical", "method": "Coinbase OAuth access token - direct API access without key signing. Can trade and withdraw.", "disclosure": "Coinbase Security: https://www.coinbase.com/security"},
        {"name": "Coinbase Refresh Token", "regex": r"COINBASE[_]?REFRESH[_]?TOKEN\s*[=:]\s*['\"]?([A-Za-z0-9]{64})['\"]?", "severity": "high", "method": "Coinbase OAuth refresh token - can generate new access tokens indefinitely. Persistent access.", "disclosure": "Coinbase Security: https://www.coinbase.com/security"},
        {"name": "Kraken API Key", "regex": r"KRAKEN[_]?API[_]?KEY\s*[=:]\s*['\"]?([A-Za-z0-9+/=]{56})['\"]?", "severity": "critical", "method": "Kraken API key for trading and account access.", "disclosure": "Kraken Security: security@kraken.com"},
        {"name": "Kraken API Secret", "regex": r"KRAKEN[_]?API[_]?SECRET\s*[=:]\s*['\"]?([A-Za-z0-9+/=]{86})['\"]?", "severity": "critical", "method": "Kraken API private key - signs requests for trading, withdrawals, and balance queries.", "disclosure": "Kraken Security: security@kraken.com"},
        {"name": "Bybit API Key", "regex": r"BYBIT[_]?API[_]?KEY\s*[=:]\s*['\"]?([A-Za-z0-9]{36})['\"]?", "severity": "critical", "method": "Bybit exchange API key for derivatives trading and withdrawals.", "disclosure": "Bybit Security: https://www.bybit.com/en/contactus"},
        {"name": "Kucoin API Key", "regex": r"KUCOIN[_]?API[_]?KEY\s*[=:]\s*['\"]?([a-f0-9]{24})['\"]?", "severity": "critical", "method": "Kucoin API key for spot/futures trading.", "disclosure": "Kucoin Security: https://www.kucoin.com/contact"},
        {"name": "Kucoin API Secret", "regex": r"KUCOIN[_]?API[_]?SECRET\s*[=:]\s*['\"]?([A-Za-z0-9-]{36})['\"]?", "severity": "critical", "method": "Kucoin API secret - signs requests for trading and withdrawals.", "disclosure": "Kucoin Security: https://www.kucoin.com/contact"},
        {"name": "Coinspot API Key", "regex": r"COINSPOT[_]?API[_]?KEY\s*[=:]\s*['\"]?([A-Za-z0-9]{20,40})['\"]?", "severity": "critical", "method": "Coinspot (Australian crypto exchange) API key. Access to trading, balance queries, and withdrawals on Coinspot.com.au.", "disclosure": "Coinspot Security: support@coinspot.com.au"},
        {"name": "Coinspot API Secret", "regex": r"COINSPOT[_]?API[_]?SECRET\s*[=:]\s*['\"]?([A-Za-z0-9]{20,64})['\"]?", "severity": "critical", "method": "Coinspot API secret - signs all API requests. Combined with API key allows full account control on Coinspot exchange.", "disclosure": "Coinspot Security: support@coinspot.com.au"},
        {"name": "Bisq Seed Node", "regex": r"BISQ[_]?SEED[_]?NODE\s*[=:]\s*['\"]?([A-Za-z0-9:.\-]{20,})['\"]?", "severity": "high", "method": "Bisq P2P exchange seed node address. Can monitor/interrupt P2P trading network.", "disclosure": "Bisq Security: https://bisq.network/security/"},
        {"name": "Bisq Wallet Private Key", "regex": r"BISQ[_]?WALLET[_]?KEY\s*[=:]\s*['\"]?([5KL][1-9A-HJ-NP-Za-km-z]{50,51})['\"]?", "severity": "critical", "method": "Bisq wallet private key (Bitcoin WIF format). Can import to any Bitcoin wallet and drain all trading funds.", "disclosure": "Bisq Security: https://bisq.network/"},
        {"name": "Bisq DAO Key", "regex": r"BISQ[_]?DAO[_]?KEY\s*[=:]\s*['\"]?([A-Za-z0-9]{32,64})['\"]?", "severity": "high", "method": "Bisq DAO key. Can participate in governance and potentially manipulate proposals.", "disclosure": "Bisq Security: https://bisq.network/"},
        {"name": "FTX API Key", "regex": r"FTX[_]?API[_]?KEY\s*[=:]\s*['\"]?([A-Za-z0-9]{32})['\"]?", "severity": "low", "method": "FTX exchange API key (FTX is defunct).", "disclosure": "N/A - FTX is defunct"},
    ],
    "crypto_wallet": [
        {"name": "Bitcoin Private Key (WIF)", "regex": r"\b([5KL][1-9A-HJ-NP-Za-km-z]{50,51})\b", "severity": "critical", "method": "Bitcoin private key in Wallet Import Format. Can import into any wallet to spend all funds.", "disclosure": "Notify owner if identifiable."},
        {"name": "Ethereum Private Key", "regex": r"\b(0x[a-fA-F0-9]{64})\b", "severity": "critical", "method": "Ethereum private key. Import to MetaMask or any ETH wallet to drain all ETH, ERC-20 tokens, and NFTs.", "disclosure": "Notify owner if identifiable."},
        {"name": "Seed Phrase (12 words)", "regex": r"\b((?:[a-z]{3,8}\s){11}[a-z]{3,8})\b", "severity": "critical", "method": "12-word BIP39 mnemonic seed phrase. Can restore any crypto wallet and drain all funds.", "disclosure": "Notify owner if identifiable."},
        {"name": "Seed Phrase (24 words)", "regex": r"\b((?:[a-z]{3,8}\s){23}[a-z]{3,8})\b", "severity": "critical", "method": "24-word BIP39 mnemonic seed phrase. Full wallet recovery - drains all cryptocurrencies and NFTs.", "disclosure": "Notify owner if identifiable."},
    ],
    "google_accounts": [
        {"name": "Google OAuth Client Secret", "regex": r"(?:GOOGLE|GOOGL)[_]?CLIENT[_]?SECRET\s*[=:]\s*['\"]?(GOCSPX-[A-Za-z0-9_-]{20,})['\"]?", "severity": "critical", "method": "Google OAuth 2.0 client secret (GOCSPX format). Can impersonate the Google OAuth app, intercept authorization flows, and gain access to victim's Google account (Gmail, Drive, Calendar, Contacts, YouTube).", "disclosure": "Google VRP: https://bughunters.google.com"},
        {"name": "Google OAuth Client ID", "regex": r"(?:GOOGLE|GOOGL)[_]?CLIENT[_]?ID\s*[=:]\s*['\"]?(\d+-[A-Za-z0-9_-]{20,}\.apps\.googleusercontent\.com)['\"]?", "severity": "high", "method": "Google OAuth client ID. Used with client secret to craft phishing URLs that appear legitimate.", "disclosure": "Google VRP: https://bughunters.google.com"},
        {"name": "Google API Key", "regex": r"GOOGLE[_]?API[_]?KEY\s*[=:]\s*['\"]?(AIza[A-Za-z0-9_-]{35})['\"]?", "severity": "high", "method": "Google API key (AIza format). Access to Google APIs - Maps, Translate, YouTube Data, Custom Search. Quota theft and data access.", "disclosure": "Google VRP: https://bughunters.google.com"},
        {"name": "Google Service Account JSON", "regex": r'"type":\s*"service_account".*"private_key":\s*"-----BEGIN PRIVATE KEY-----', "severity": "critical", "method": "Google Cloud service account JSON key. Full access to the GCP project - Compute Engine, Storage, BigQuery, IAM, Secrets Manager. Can create new service accounts for persistent access.", "disclosure": "Google VRP: https://bughunters.google.com"},
        {"name": "Google Access Token", "regex": r"GOOGLE[_]?ACCESS[_]?TOKEN\s*[=:]\s*['\"]?(ya29\.[A-Za-z0-9_-]{20,})['\"]?", "severity": "high", "method": "Google OAuth access token (ya29 format). Direct access to Google APIs on behalf of the token owner. Can read Gmail, access Drive files, manage Calendar.", "disclosure": "Google VRP: https://bughunters.google.com"},
        {"name": "Google Refresh Token", "regex": r"GOOGLE[_]?REFRESH[_]?TOKEN\s*[=:]\s*['\"]?(1//[A-Za-z0-9_-]{20,})['\"]?", "severity": "critical", "method": "Google OAuth refresh token (1// format). Can generate new access tokens indefinitely. Persistent access to victim's Google account.", "disclosure": "Google VRP: https://bughunters.google.com"},
        {"name": "Firebase API Key", "regex": r"FIREBASE[_]?API[_]?KEY\s*[=:]\s*['\"]?(AIza[A-Za-z0-9_-]{35})['\"]?", "severity": "high", "method": "Firebase API key. Access to Firebase project - Firestore database, Authentication, Cloud Messaging. Can read/write database records.", "disclosure": "Firebase Security: https://firebase.google.com/support/security"},
        {"name": "Firebase Service Account", "regex": r"FIREBASE[_]?SERVICE[_]?ACCOUNT\s*[=:]\s*['\"]?(firebase-adminsdk-[A-Za-z0-9_-]+\.iam\.gserviceaccount\.com)['\"]?", "severity": "critical", "method": "Firebase admin service account. Full admin access to Firebase project - database, auth, storage, messaging.", "disclosure": "Firebase Security: https://firebase.google.com/support/security"},
        {"name": "Google Cloud Storage Key", "regex": r"GOOGLE[_]?STORAGE[_]?KEY\s*[=:]\s*['\"]?(GOOG[A-Za-z0-9]{16,})['\"]?", "severity": "high", "method": "Google Cloud Storage HMAC key (GOOG format). Access to GCS buckets - read/write/delete objects.", "disclosure": "Google VRP: https://bughunters.google.com"},
    ],
    "microsoft_accounts": [
        {"name": "Azure AD Client Secret", "regex": r"AZURE[_]?CLIENT[_]?SECRET\s*[=:]\s*['\"]?([A-Za-z0-9_\-~.]{20,})['\"]?", "severity": "critical", "method": "Azure AD (Entra ID) client secret. Can authenticate as the service principal to access Microsoft Graph, Azure resources, and M365 services. Full tenant access depending on app permissions.", "disclosure": "Microsoft Security: https://www.microsoft.com/en-us/msrc"},
        {"name": "Azure AD Client ID", "regex": r"AZURE[_]?CLIENT[_]?ID\s*[=:]\s*['\"]?([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})['\"]?", "severity": "high", "method": "Azure AD application client ID (UUID format). Combined with client secret to authenticate to Azure AD tenant.", "disclosure": "Microsoft Security: https://www.microsoft.com/en-us/msrc"},
        {"name": "Azure AD Tenant ID", "regex": r"AZURE[_]?TENANT[_]?ID\s*[=:]\s*['\"]?([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})['\"]?", "severity": "medium", "method": "Azure AD tenant ID. Identifies the Azure AD instance. Combined with client ID and secret for full authentication.", "disclosure": "Microsoft Security: https://www.microsoft.com/en-us/msrc"},
        {"name": "Azure Storage Key", "regex": r"AZURE[_]?STORAGE[_]?KEY\s*[=:]\s*['\"]?([A-Za-z0-9+/=]{88})['\"]?", "severity": "critical", "method": "Azure Storage account key (base64, 88 chars). Full access to Azure Storage - Blob, Queue, Table, File shares. Read/write/delete all data.", "disclosure": "Microsoft Security: https://www.microsoft.com/en-us/msrc"},
        {"name": "Azure Storage Connection String", "regex": r"(DefaultEndpointsProtocol=https?;AccountName=[^;]+;AccountKey=[A-Za-z0-9+/=]{88})", "severity": "critical", "method": "Azure Storage connection string. Direct access to Azure Storage account - blobs, queues, tables. Full read/write/delete.", "disclosure": "Microsoft Security: https://www.microsoft.com/en-us/msrc"},
        {"name": "Microsoft Graph Token", "regex": r"MICROSOFT[_]?GRAPH[_]?TOKEN\s*[=:]\s*['\"]?(eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,})['\"]?", "severity": "critical", "method": "Microsoft Graph API access token (JWT). Can read emails, files, calendar, Teams messages, and organizational data via Microsoft Graph.", "disclosure": "Microsoft Security: https://www.microsoft.com/en-us/msrc"},
        {"name": "Azure Subscription ID", "regex": r"AZURE[_]?SUBSCRIPTION[_]?ID\s*[=:]\s*['\"]?([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})['\"]?", "severity": "medium", "method": "Azure subscription ID. Identifies the Azure subscription. Combined with client credentials for full Azure management access.", "disclosure": "Microsoft Security: https://www.microsoft.com/en-us/msrc"},
        {"name": "MS Teams Webhook URL", "regex": r"(https://[a-z0-9]+\.webhook\.office\.com/webhookb2/[A-Za-z0-9-]+@[A-Za-z0-9-]+/[A-Za-z0-9-]+/[A-Za-z0-9-]+)", "severity": "medium", "method": "Microsoft Teams incoming webhook URL. Can send messages to the Teams channel without authentication.", "disclosure": "Microsoft Security: https://www.microsoft.com/en-us/msrc"},
        {"name": "Azure Function Key", "regex": r"AZURE[_]?FUNCTION[_]?KEY\s*[=:]\s*['\"]?([A-Za-z0-9+/=]{40,})['\"]?", "severity": "high", "method": "Azure Functions host key. Can invoke any function in the Function App. May trigger backend operations.", "disclosure": "Microsoft Security: https://www.microsoft.com/en-us/msrc"},
    ],
    "social_media": [
        {"name": "Facebook Access Token", "regex": r"\b(EAAG[a-zA-Z0-9]{20,})\b", "severity": "high", "method": "Facebook Graph API access token. Can read user profile, posts, messages, and post on behalf of the user.", "disclosure": "Meta Security: https://www.meta.com/security/"},
        {"name": "Facebook App Secret", "regex": r"FACEBOOK[_]?APP[_]?SECRET\s*[=:]\s*['\"]?([a-f0-9]{32})['\"]?", "severity": "high", "method": "Facebook app secret - signs API requests. Can generate access tokens for any app user.", "disclosure": "Meta Security: https://www.meta.com/security/"},
        {"name": "Twitter Bearer Token", "regex": r"\b(AAAA[a-zA-Z0-9]{%1,40})\b", "severity": "high", "method": "Twitter/X API bearer token. App-level access to Twitter API - read tweets, DMs, user data.", "disclosure": "Twitter/X Security: https://help.twitter.com/en/safety-and-security"},
        {"name": "Instagram Access Token", "regex": r"INSTAGRAM[_]?ACCESS[_]?TOKEN\s*[=:]\s*['\"]?(IGQVJ[A-Za-z0-9_]{20,})['\"]?", "severity": "high", "method": "Instagram Graph API token. Can read profile, posts, stories, and DMs.", "disclosure": "Instagram/Meta Security: https://help.instagram.com/368021276864178"},
        {"name": "Discord Bot Token", "regex": r"\b([A-Za-z0-9]{24}\.[A-Za-z0-9_]{6}\.[A-Za-z0-9_]{27})\b", "severity": "high", "method": "Discord bot token. Full control of the bot account - read messages, send messages, access guilds.", "disclosure": "Discord Trust & Safety: https://discord.com/safety"},
        {"name": "Discord Webhook URL", "regex": r"(https://discord(?:app)?\.com/api/webhooks/\d+/[A-Za-z0-9_-]+)", "severity": "medium", "method": "Discord webhook URL. Can send messages to the channel without authentication.", "disclosure": "Discord Trust & Safety: https://discord.com/safety"},
        {"name": "Telegram Bot Token", "regex": r"\b(\d{8,10}:AA[A-Za-z0-9_-]{33,35})\b", "severity": "high", "method": "Telegram bot token. Full control of the bot - send messages, read chats, access group data.", "disclosure": "Telegram Security: https://telegram.org/abuse"},
        {"name": "Snapchat API Token", "regex": r"SNAPCHAT[_]?API[_]?TOKEN\s*[=:]\s*['\"]?([A-Za-z0-9_\-]{15,})['\"]?", "severity": "high", "method": "Snapchat API token. Access to Snapchat Marketing API or Snap Kit - can access user data, ad accounts, and campaign data.", "disclosure": "Snap Security: security@snap.com"},
        {"name": "Snapchat Client Secret", "regex": r"SNAPCHAT[_]?CLIENT[_]?SECRET\s*[=:]\s*['\"]?([a-f0-9]{32,64})['\"]?", "severity": "high", "method": "Snapchat OAuth client secret. Can generate access tokens for Snapchat users via Snap Login Kit.", "disclosure": "Snap Security: security@snap.com"},
        {"name": "Snapchat Client ID", "regex": r"SNAPCHAT[_]?CLIENT[_]?ID\s*[=:]\s*['\"]?([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})['\"]?", "severity": "medium", "method": "Snapchat OAuth client ID (UUID). Combined with client secret for Snap Kit OAuth flows.", "disclosure": "Snap Security: security@snap.com"},
        {"name": "Snapchat Refresh Token", "regex": r"SNAPCHAT[_]?REFRESH[_]?TOKEN\s*[=:]\s*['\"]?([A-Za-z0-9_\-]{20,})['\"]?", "severity": "high", "method": "Snapchat OAuth refresh token. Can generate new access tokens for persistent Snapchat API access.", "disclosure": "Snap Security: security@snap.com"},
        {"name": "Reddit API Secret", "regex": r"REDDIT[_]?API[_]?SECRET\s*[=:]\s*['\"]?([A-Za-z0-9]{27})['\"]?", "severity": "medium", "method": "Reddit API client secret. Access to Reddit API for reading/moderating subreddits.", "disclosure": "Reddit Security: https://www.reddit.com/security"},
        {"name": "TikTok Access Token", "regex": r"TIKTOK[_]?ACCESS[_]?TOKEN\s*[=:]\s*['\"]?(tt[A-Za-z0-9_]{20,})['\"]?", "severity": "high", "method": "TikTok API access token. Can read user profile, video data, and post content.", "disclosure": "TikTok Security: https://www.tiktok.com/safety/en/"},
        {"name": "LinkedIn Access Token", "regex": r"LINKEDIN[_]?ACCESS[_]?TOKEN\s*[=:]\s*['\"]?(AQ[A-Za-z0-9_]{20,})['\"]?", "severity": "high", "method": "LinkedIn API access token. Can read profile, connections, and post on behalf of user.", "disclosure": "LinkedIn Security: https://www.linkedin.com/help/linkedin/ask/TS-aha"},
    ],
    "telco_australian": [
        {"name": "Telstra API Key", "regex": r"TELSTRA[_]?API[_]?KEY\s*[=:]\s*['\"]?([A-Za-z0-9]{20,})['\"]?", "severity": "high", "method": "Telstra API key - access to Telstra dev APIs including SMS, voice, and messaging services.", "disclosure": "Telstra Security: https://www.telstra.com.au/security"},
        {"name": "Telstra OAuth Secret", "regex": r"TELSTRA[_]?CLIENT[_]?SECRET\s*[=:]\s*['\"]?([A-Za-z0-9]{20,})['\"]?", "severity": "high", "method": "Telstra OAuth client secret - can generate access tokens for Telstra API services.", "disclosure": "Telstra Security: https://www.telstra.com.au/security"},
        {"name": "Optus API Key", "regex": r"OPTUS[_]?API[_]?KEY\s*[=:]\s*['\"]?([A-Za-z0-9]{20,})['\"]?", "severity": "high", "method": "Optus API key - access to Optus mobile and internet service APIs.", "disclosure": "Optus Security: security@optus.com.au"},
        {"name": "Vodafone AU API Key", "regex": r"VODAFONE[_]?AU[_]?API[_]?KEY\s*[=:]\s*['\"]?([A-Za-z0-9]{20,})['\"]?", "severity": "high", "method": "Vodafone Australia API key - access to Vodafone AU mobile account services.", "disclosure": "Vodafone AU Security: https://www.vodafone.com.au/security"},
        {"name": "Twilio Auth Token", "regex": r"TWILIO[_]?AUTH[_]?TOKEN\s*[=:]\s*['\"]?([a-f0-9]{32})['\"]?", "severity": "high", "method": "Twilio auth token - can send SMS, make calls, and access account data via Twilio API.", "disclosure": "Twilio Security: https://twilio.com/security"},
        {"name": "Twilio Account SID", "regex": r"TWILIO[_]?ACCOUNT[_]?SID\s*[=:]\s*['\"]?(AC[a-f0-9]{32})['\"]?", "severity": "medium", "method": "Twilio account SID. Combined with auth token gives full API access.", "disclosure": "Twilio Security: https://twilio.com/security"},
    ],
    "server_infrastructure": [
        {"name": "AWS Access Key ID", "regex": r"\b(AKIA[0-9A-Z]{16})\b", "severity": "critical", "method": "AWS access key ID. Combined with secret access key gives full AWS account access - S3, EC2, RDS, IAM, everything.", "disclosure": "AWS Security: https://aws.amazon.com/security/"},
        {"name": "AWS Secret Access Key", "regex": r"aws[_]?secret[_]?access[_]?key\s*[=:]\s*['\"]?([A-Za-z0-9/+=]{40})['\"]?", "severity": "critical", "method": "AWS secret access key - signs all AWS API requests. Full account compromise when paired with access key ID.", "disclosure": "AWS Security: https://aws.amazon.com/security/"},
        {"name": "AWS Session Token", "regex": r"aws[_]?session[_]?token\s*[=:]\s*['\"]?(Fwo[A-Za-z0-9+/=]{50,})['\"]?", "severity": "critical", "method": "AWS temporary session token from STS. Grants short-lived but full AWS access.", "disclosure": "AWS Security: https://aws.amazon.com/security/"},
        {"name": "Private Key Block", "regex": r"(-----BEGIN (?:RSA |EC |DSA |OPENSSH |PGP )?PRIVATE KEY-----[\s\S]*?-----END (?:RSA |EC |DSA |OPENSSH |PGP )?PRIVATE KEY-----)", "severity": "critical", "method": "Private key file - SSH, SSL/TLS, or PGP. Can authenticate to servers, decrypt traffic, or sign messages.", "disclosure": "Notify infrastructure owner immediately."},
        {"name": "DigitalOcean Token", "regex": r"DIGITALOCEAN[_]?TOKEN\s*[=:]\s*['\"]?(dop_v[A-Za-z0-9_]{20,}|do_v[A-Za-z0-9_]{20,})['\"]?", "severity": "critical", "method": "DigitalOcean API token. Full access to droplets, networking, storage, and DNS management.", "disclosure": "DigitalOcean Security: https://www.digitalocean.com/security"},
    ],
    "database": [
        {"name": "MongoDB Connection String", "regex": r"(mongodb(?:\+srv)?:\/\/[^:]+:[^@]+@[^\s\"']+)", "severity": "critical", "method": "MongoDB connection string with credentials. Direct database access - read, write, delete all data.", "disclosure": "MongoDB Security: https://www.mongodb.com/security"},
        {"name": "PostgreSQL Connection", "regex": r"(postgres(?:ql)?:\/\/[^:]+:[^@]+@[^\s\"']+)", "severity": "critical", "method": "PostgreSQL connection string with password. Full database access.", "disclosure": "Notify database owner immediately."},
        {"name": "MySQL Connection", "regex": r"(mysql:\/\/[^:]+:[^@]+@[^\s\"']+)", "severity": "critical", "method": "MySQL connection string with credentials. Full database access.", "disclosure": "Notify database owner immediately."},
    ],
    "payment": [
        {"name": "Stripe Secret Key", "regex": r"STRIPE[_]?SECRET[_]?KEY\s*[=:]\s*['\"]?(sk_live_[A-Za-z0-9]{20,})['\"]?", "severity": "critical", "method": "Stripe live secret key. Can process payments, issue refunds, create charges, and access all customer payment data.", "disclosure": "Stripe Bug Bounty: https://hackerone.com/stripe"},
        {"name": "PayPal Client Secret", "regex": r"PAYPAL[_]?CLIENT[_]?SECRET\s*[=:]\s*['\"]?(EH[A-Za-z0-9_\-]{20,})['\"]?", "severity": "critical", "method": "PayPal API client secret. Can process payments, issue refunds, and access account balances.", "disclosure": "PayPal Security: https://www.paypal.com/security"},
        {"name": "Square API Key", "regex": r"SQUARE[_]?API[_]?KEY\s*[=:]\s*['\"]?(sq0atp-[A-Za-z0-9_\-]{22})['\"]?", "severity": "critical", "method": "Square API access token. Can process payments, manage orders, and access merchant data.", "disclosure": "Square Security: https://squareup.com/security"},
    ],
    "ai_services": [
        {"name": "OpenAI API Key", "regex": r"\b(sk-[A-Za-z0-9]{20,})\b", "severity": "high", "method": "OpenAI API key (sk- format). Can access GPT models, DALL-E, Whisper. Quota theft and cost accumulation.", "disclosure": "OpenAI Security: https://openai.com/security/"},
        {"name": "Anthropic API Key", "regex": r"\b(sk-ant-[A-Za-z0-9_-]{20,})\b", "severity": "high", "method": "Anthropic API key (sk-ant- format). Access to Claude models. Quota theft.", "disclosure": "Anthropic Security: https://anthropic.com/security"},
        {"name": "HuggingFace Token", "regex": r"HUGGING[_]?FACE[_]?TOKEN\s*[=:]\s*['\"]?(hf_[A-Za-z0-9]{20,})['\"]?", "severity": "medium", "method": "Hugging Face access token. Can access private models, datasets, and spaces.", "disclosure": "HuggingFace Security: https://huggingface.co/security"},
    ],
}

DORK_QUERIES = {
    "database": [
        'filetype:env "DATABASE_URL"',
        'filetype:env "MONGO_URI"',
        'filetype:env "MONGODB_URI"',
        'filetype:env "REDIS_URL"',
        'filetype:env "POSTGRES"',
        'filetype:env "MYSQL"',
        'intitle:"index of" ".env"',
        'filetype:sql "INSERT INTO" "password"',
    ],
    "crypto_exchange": [
        'filetype:env "BINANCE_API"',
        'filetype:env "COINBASE_API"',
        'filetype:env "COINBASE_ACCESS_TOKEN"',
        'filetype:env "COINBASE_REFRESH_TOKEN"',
        'filetype:env "KRAKEN_API"',
        'filetype:env "BYBIT_API"',
        'filetype:env "KUCOIN_API"',
        'filetype:env "COINSPOT_API"',
        'filetype:env "BISQ_"',
        'filetype:json "binance" "api_key" "secret"',
        'filetype:json "coinbase" "access_token"',
        'filetype:json "coinspot" "api_key"',
        'filetype:env "BITFINEX_API"',
        'ext:json "bisq" "wallet" "key"',
    ],
    "crypto_wallet": [
        'filetype:json "private_key"',
        'ext:txt "wallet.dat"',
        'filetype:env "MNEMONIC"',
        'filetype:env "SEED_PHRASE"',
        'filetype:txt "5K" "Bitcoin"',
    ],
    "google_accounts": [
        'filetype:env "GOOGLE_CLIENT_SECRET"',
        'filetype:env "GOOGLE_CLIENT_ID"',
        'filetype:env "GOOGLE_API_KEY"',
        'filetype:env "GOOGLE_ACCESS_TOKEN"',
        'filetype:env "GOOGLE_REFRESH_TOKEN"',
        'filetype:env "FIREBASE_API_KEY"',
        'filetype:json "type": "service_account"',
        'filetype:json "private_key" "client_email" "google"',
        'filetype:env "GOOGLE_CLOUD_KEY"',
        'filetype:env "GOOGLE_STORAGE_KEY"',
        'ext:json "firebase" "service_account"',
    ],
    "microsoft_accounts": [
        'filetype:env "AZURE_CLIENT_SECRET"',
        'filetype:env "AZURE_CLIENT_ID"',
        'filetype:env "AZURE_TENANT_ID"',
        'filetype:env "AZURE_STORAGE_KEY"',
        'filetype:env "AZURE_SUBSCRIPTION_ID"',
        'filetype:env "AZURE_FUNCTION_KEY"',
        'filetype:json "azure" "client_secret" "tenant"',
        'filetype:env "MICROSOFT_GRAPH_TOKEN"',
        'filetype:env "OUTLOOK_API_TOKEN"',
        'ext:json "azure" "connectionString" "AccountKey"',
    ],
    "server": [
        'filetype:env "SSH_PRIVATE_KEY"',
        'filetype:pem "PRIVATE KEY"',
        'filetype:env "AWS_SECRET_ACCESS_KEY"',
        'filetype:env "AWS_ACCESS_KEY_ID"',
        'filetype:env "DIGITALOCEAN_ACCESS_TOKEN"',
        'filetype:env "GCP_SERVICE_ACCOUNT"',
        'filetype:env "HEROKU_API_KEY"',
    ],
    "social_media": [
        'filetype:env "FACEBOOK_ACCESS_TOKEN"',
        'filetype:env "TWITTER_BEARER_TOKEN"',
        'filetype:env "INSTAGRAM_ACCESS_TOKEN"',
        'filetype:env "DISCORD_BOT_TOKEN"',
        'filetype:env "TELEGRAM_BOT_TOKEN"',
        'filetype:env "SNAPCHAT_API_TOKEN"',
        'filetype:env "SNAPCHAT_CLIENT_SECRET"',
        'filetype:env "SNAPCHAT_CLIENT_ID"',
        'filetype:env "SNAPCHAT_REFRESH_TOKEN"',
        'filetype:env "TIKTOK_ACCESS_TOKEN"',
        'filetype:env "LINKEDIN_ACCESS_TOKEN"',
        'filetype:env "REDDIT_API_SECRET"',
    ],
    "telco": [
        'filetype:env "TELSTRA_API"',
        'filetype:env "OPTUS_API"',
        'filetype:env "VODAFONE_API"',
        'filetype:env "TWILIO_AUTH_TOKEN"',
    ],
    "payment": [
        'filetype:env "STRIPE_SECRET_KEY"',
        'filetype:env "PAYPAL_CLIENT_SECRET"',
        'filetype:env "SQUARE_API_KEY"',
    ],
    "ai_services": [
        'filetype:env "OPENAI_API_KEY"',
        'filetype:env "ANTHROPIC_API_KEY"',
        'filetype:env "HUGGING_FACE_TOKEN"',
    ],
    "config": [
        'intitle:"index of" "config.php"',
        'intitle:"index of" "settings.py"',
        'intitle:"index of" "wp-config.php"',
        'intitle:"index of" "application.yml"',
        'intitle:"index of" "credentials"',
    ],
    "api_keys": [
        'filetype:json "api_key" "secret"',
        'filetype:yaml "api_key:" "secret:"',
        'filetype:env "API_SECRET"',
        'filetype:env "GITHUB_TOKEN"',
        'filetype:env "SLACK_TOKEN"',
    ],
}

GITHUB_DORKS = [
    'GOOGLE_CLIENT_SECRET filename:.env',
    'GOOGLE_CLIENT_ID filename:.env',
    'GOOGLE_API_KEY filename:.env',
    'GOOGLE_ACCESS_TOKEN filename:.env',
    'GOOGLE_REFRESH_TOKEN filename:.env',
    'GOCSPX- filename:.env',
    'AIza filename:.env "google"',
    '"type": "service_account" "private_key" filename:json',
    'FIREBASE_API_KEY filename:.env',
    'AZURE_CLIENT_SECRET filename:.env',
    'AZURE_CLIENT_ID filename:.env',
    'AZURE_TENANT_ID filename:.env',
    'AZURE_STORAGE_KEY filename:.env',
    'DefaultEndpointsProtocol AccountName AccountKey',
    'COINBASE_API_KEY filename:.env',
    'COINBASE_API_SECRET filename:.env',
    'COINBASE_ACCESS_TOKEN filename:.env',
    'COINBASE_REFRESH_TOKEN filename:.env',
    'COINSPOT_API_KEY filename:.env',
    'COINSPOT_API_SECRET filename:.env',
    'BISQ_WALLET_KEY filename:.env',
    'BISQ_DAO_KEY filename:.env',
    'SNAPCHAT_API_TOKEN filename:.env',
    'SNAPCHAT_CLIENT_SECRET filename:.env',
    'SNAPCHAT_CLIENT_ID filename:.env',
    'SNAPCHAT_REFRESH_TOKEN filename:.env',
    'BINANCE_API_KEY filename:.env',
    'KRAKEN_API_SECRET filename:.env',
    'STRIPE_SECRET_KEY filename:.env',
    'OPENAI_API_KEY filename:.env',
]
